spring:
  application:
    name: Lab-app
  datasource:
    username: postgres
    password: example
    url: jdbc:postgresql://localhost:5432/lab7
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  port: 8080

keycloak:
  realm: MyProject
  auth-server-url: http://localhost:18080/auth
  resource: my-app-client
  public-client: true
  bearer-only: true